I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 11, in script call
    call D1S1
  File "game/scenes/scenes/D3S3.rpy", line 47, in script
    jump D3S4c
ScriptError: could not find label 'D3S4c'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 11, in script call
    call D1S1
  File "game/scenes/scenes/D3S3.rpy", line 47, in script
    jump D3S4c
  File "/Users/alexolthoff/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 1705, in execute
    rv = renpy.game.script.lookup(target)
  File "/Users/alexolthoff/Desktop/renpy-8.3.4-sdk/renpy/script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'D3S4c'.

macOS-14.3-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Lyceum of Leviathans 1.0
Fri Jan 31 01:08:12 2025
